version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      # Restore cache for dependencies
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "pyproject.toml" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      # Upgrade pip
      - run:
          name: Install pip
          command: |
            python -m pip install --upgrade pip
      # Install project dependencies (including dev dependencies)
      - run:
          name: Install Dependencies
          command: |
            pip install -e ".[dev]"
      # Save cache for dependencies
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "pyproject.toml" }}
          paths:
            - ~/.cache/pip
            - ~/.local/lib/python3.12/site-packages
      # Run static analysis (ruff and mypy)
      - run:
          name: Run Static Analysis
          command: |
            ruff check .
            mypy .
      # Run unit tests with coverage
      - run:
          name: Run Unit Tests
          command: |
            mkdir -p test-results/unit
            pytest tests/unit/ --cov=src --cov-report=html:coverage_html --junitxml=test-results/unit/junit.xml
      # Run integration tests with coverage
      - run:
          name: Run Integration Tests
          command: |
            mkdir -p test-results/integration
            pytest tests/integration/ --cov=src --cov-append --cov-report=html:coverage_html --junitxml=test-results/integration/junit.xml
      # Run end-to-end tests with coverage
      - run:
          name: Run End-to-End Tests
          command: |
            mkdir -p test-results/e2e
            pytest tests/e2e/ --cov=src --cov-append --cov-report=html:coverage_html --junitxml=test-results/e2e/junit.xml
      # Store test results for all test types (unit, integration, e2e)
      - store_test_results:
          path: test-results
      # Store coverage HTML report
      - store_artifacts:
          path: coverage_html
          destination: coverage-html-report
      # Store test results as artifacts for debugging
      - store_artifacts:
          path: test-results
          destination: test-results

workflows:
  test_and_deploy:
    jobs:
      - build_and_test
